# Generated by Django 3.1.4 on 2020-12-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20201216_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower_accepted_at',
            field=models.DateField(null=True),
        ),
    ]
