# Generated by Django 3.1.4 on 2020-12-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20201216_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='total_loan_amount',
            new_name='borrower_payments_till_now',
        ),
    ]
