# Generated by Django 3.1.4 on 2020-12-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20201217_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower_payments_till_now',
            field=models.IntegerField(default=0),
        ),
    ]
